### PR TITLE
Made the JDL files a bit simpler

### PR DESCRIPTION
**Pull request by MathieuAA**

### CODE REVIEW

**Comment by jdubois** [comment]
As I'm using those for Devoxx, and I just finished testing everything - can we wait until Devoxx is finish to merge those? I don't want to re-test everything...

**Comment by MathieuAA** [comment]
@jdubois Okay, but I promise you they are good to go ;)

**Comment by jdubois** [comment]
Oops I totally missed this!!
Sorry @MathieuAA I'm merging this now

**Comment by MathieuAA** [comment]
I totally forgot this PR!! I guess there was no urgency :) thanks Julien!I've got to come up with a new base JDL example one day

**Pull request merged**
