### PR TITLE
Add reactive microfrontends JDL

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@mshima - I remember you saying there was flag you could use to override the `clientFramework` settings in a file like this. Do you remember what that flag is?

**Comment by mshima** [comment]
@mraible do you mean `jhipster jdl ms-stack.jdl --client-framework react|angularX|vue`?

**Comment by mraible** [comment]
That's it! I thought it didn't work because I was using `angular` instead of `angularX`.

**Comment by mshima** [comment]
We should change the config value to angular. There is no need to name it angularX.

**Comment by mraible** [comment]
@mshima Can you override any values with parameters or only certain ones? This doesn't work:

```
jhipster jdl blog-oauth2.jdl --reactive true
```

Result:

```
INFO! File not found: blog-oauth2.jdl. Attempting download from jdl-samples repository
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/v7.8.1/blog-oauth2.jdl
INFO! File not found: true.jdl. Attempting download from jdl-samples repository
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/v7.8.1/true.jdl
INFO! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/v7.8.1/true.jdl: 404 - Not Found
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/main/true.jdl
ERROR! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/true.jdl: 404 - Not Found
Error: Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/true.jdl: 404 - Not Found
    at ClientRequest.<anonymous> (/Users/mraible/dev/generator-jhipster/cli/download.js:33:25)
```

**Comment by mshima** [comment]
@mraible reactive option doesn't take a value (true is being used as a jdl file).
```
jhipster jdl blog-oauth2.jdl --reactive
```
to disable
```
jhipster jdl blog-oauth2.jdl --no-reactive
```

**Pull request merged**
